version: '2'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'myDb'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'mysqlpass'
    ports:
      - 3306:3306