version: '2'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'myDb'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'mysqlpass'
    ports:
      - 3306:3306
    volumes:
      - ./data/mysqldb:/var/lib/mysql
      